### ISSUE TITLE
DotNet Core

### ISSUE THREAD

**Issue by davek17** [esendex/esendex-dotnet-sdk#22]
Hi,

I've done some work around a dotnet core version as a subproject in [https://github.com/dktc/esendex-dotnet-sdk](dktc/esendex-dotnet-sdk) I've been using it to send SMS messages and it builds OK, but I didn't want to publish as a pull request as I've only tested a small section of it, the bits I need.

Anyway, thought I'd let you know in case you want to use it as a starting block for future dev work.

**Comment by SLStinson** [comment]
Hi @davek17! 

Thank you very much for pointing us at this. If your fork gets to a point where you feel it is mature enough to be ready for a pull request we would be happy to review it. 

Dot net core support has been raised before. At this time we aren't actively developing anything, however this is likely to change in the future.
